### ISSUE TITLE
Support for 16x32 boards? 

### ISSUE THREAD

**Issue by sleep-sort** [Howchoo/crypto-ticker#13]
Hi there! This is such an awesome project, great work. I'm attempting to use with a smaller board, 16x32. I've changed the frame.py file but I'm still just getting two big green lines on my panel. Anywhere else I should tweak to get it working with 16x32? Thanks in advance!

**Comment by josephtyler** [comment]
Using steps 8 and 9 from this guide, are you able to run a "Hello world" test? https://howchoo.com/pi/raspberry-pi-led-matrix-panel#install-the-rpi-rgb-led-matrix-library

**Comment by sleep-sort** [comment]
that's the weird thing, I've used this library a decent amount in the past without any issues! Any of the samples in `bindings/python/samples` run perfectly fine, but then, when I run this line from your guide `sudo python3 runtext.py --led-cols=64 --led-gpio-mapping=adafruit-hat --text="Hello, world!"` I get two green lines and nothing else. 

I'm wondering if it's: 
1. Somehow my python versioning is causing things to be strange (this has happened before with this library, although I'm able to use python3 to call all the other sample scripts just fine
2. led-gpio-mapping=adafruit-hat is somehow not working for me for some reason, perhaps incorrectly wired or just not compatible? Do you have any insight on this potentially being an issue? I've not explored it yet 
Anyways, thanks so much for the help here! this project is super cool, really hoping to get it working on my machine

**Comment by josephtyler** [comment]
It could be the gpio mapping. Which panel do you have, and can you try some other mappings? I don't have too much guidance here sadly. Most of my work on this project is around price fetching and building the canvas, but the matrix code is lifted.
