### ISSUE TITLE
BTC as a currency

### ISSUE THREAD

**Issue by oblacoder** [Howchoo/crypto-ticker#16]
Many thanks for the great work for us crypto lovers!

When you make a switch to BTC as an hard money and when you understand that all other fiat currencies are total garbage and will eventually go to zero,  the only currency becomes the bitcoin itself.

Thus, for pricing of alts, we should have the bitcoin as a reference currency (both API's support this).

Any plans to enable alts pricing in btc?

Keep up the good work :)

**Comment by josephtyler** [comment]
Ha, I appreciate the enthusiasm about Bitcoin. And I agree that it's the hardest money that the Earth has ever seen. I have no plans to make this change, but I might sneak it in soon if I get some extra time.
