### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by Zach1812** [Howchoo/crypto-ticker#17]
I've been looking this over but can't understand it's output format. Ideally I would be able to output this ticker to i2c/spi/hdmi, but am unsure how that works.

Am I missing something?

**Comment by josephtyler** [comment]
This is built very specifically for an LED matrix. I tried to abstract code into various files that might be able to be modified for other types of displays in the future. `frame.py` is mostly a wrapper for the `RGBMatrix` library. `price_apis.py` intends to abstract out the code that actually fetches prices. `ticker.py` sort of ties everything together.

If you wanted to use this on a different display, you could look at `ticker.py` and start with the `run` method.
