### ISSUE TITLE
Using CoinGek API I noticed [UNI] does not work

### ISSUE THREAD

**Issue by 01010100cc** [Howchoo/crypto-ticker#18]
The API returned a price to 1 decimal place which seemed to break the ticker.

**Comment by josephtyler** [comment]
I finally got some time to look at this one. The issue wasn't that the price was returned with only 1 decimal place, but rather that there are 3+ currencies that match the "uni" symbol. And one of those doesn't return the expected data in the API response. To fix this, I added the ability to specify which currency you want in the settings.yml file. So for uniswap, you'd do something like this:

```
SYMBOLS=btc,eth,uni:uniswap
```

Here's the PR: https://github.com/Howchoo/crypto-ticker/pull/21

Once this gets merged you should be able to pull master, updated your settings, and be good to go. Let me know if this doesn't work for you.

**Comment by 01010100cc** [comment]
Perfect, thanks for the work/ fix!
