### ISSUE TITLE
Change currency $ to €

### ISSUE THREAD

**Issue by tamkar1982** [Howchoo/crypto-ticker#6]
Hi, is it possible to change the currency from $ to €?

**Comment by josephtyler** [comment]
This is going to depend on the API you're using. Supposing the API sends back prices in Euros it should be fairly straightforward to ensure the display code supports it.

**Comment by tamkar1982** [comment]
Fixed my issue!
It was hard coded in the "price_apis.py"

**Comment by josephtyler** [comment]
Perfect!

**Comment by josephtyler** [comment]
I added a PR to formally support this feature. When this gets merged you will be able to add "CURRENCY=eur" to the settings.env file to display prices in euros.
