### ISSUE TITLE
When BTC hits 6 digits...

### ISSUE THREAD

**Issue by tamkar1982** [Howchoo/crypto-ticker#8]
What will happen on the screen when BTC hits 6 digits?

**Comment by josephtyler** [comment]
I buy a new house?

**Comment by josephtyler** [comment]
> I buy a new house?

Kidding. I built this when Bitcoin was around $13k, and I was aware of the possible issue. It was more of a "cross that bridge when we get there". With that said, it may happen sooner than later. I'll have to go in and dynamically adjust the font size based on the number of digits in the price.

**Comment by tamkar1982** [comment]
Ok me too!
So everybody could update his project at the end of 2021 after BTC gets 6 digits and everything will be fine ^^
